import React from 'react';
import { fireEvent, render, screen, waitFor } from '@testing-library/react';
import { beforeEach, expect, it, vi } from 'vitest';
import Memories from '@/components/memories';
import { api } from '@/lib/api';
vi.mock('@/lib/api', () => ({ api: { memories: vi.fn(), addMemory: vi.fn(), editMemory: vi.fn(), deleteMemory: vi.fn() }, errorText: (e: Error) => e.message }));
const item = { id: 9, content: '喜欢花园', created_at: '', updated_at: '' };
it.each([false, true])('keeps an over-limit memory draft without saving (editing=%s)', async editing => {
  render(<Memories id={1} close={vi.fn()} />);
  await screen.findByText('喜欢花园');
  if (editing) fireEvent.click(screen.getByLabelText('编辑记忆：喜欢花园'));
  const field = screen.getByLabelText(editing ? '修改这条记忆' : '留下一条记忆');
  const value = '🌱'.repeat(1001);
  fireEvent.change(field, { target: { value } });
  expect(field).toHaveValue(value);
  expect(field).not.toHaveAttribute('maxlength');
  expect(screen.getByText('1001/1000')).toBeInTheDocument();
  expect(screen.getByText('记忆不能超过 1000 字')).toBeInTheDocument();
  expect(screen.getByRole('button', { name: '保存记忆' })).toBeDisabled();
  fireEvent.submit(field.closest('form')!);
  expect(api.addMemory).not.toHaveBeenCalled();
  expect(api.editMemory).not.toHaveBeenCalled();
  fireEvent.change(field, { target: { value: '🌱'.repeat(1000) } });
  expect(screen.getByRole('button', { name: '保存记忆' })).toBeEnabled();
});
it('saves a normalized 1000 emoji memory only after composition ends', async () => {
  vi.mocked(api.addMemory).mockResolvedValue(item);
  render(<Memories id={1} close={vi.fn()} />);
  await screen.findByText('喜欢花园');
  const field = screen.getByLabelText('留下一条记忆');
  fireEvent.change(field, { target: { value: ' \ufeff' + '🌱'.repeat(1000) + '　' } });
  fireEvent.compositionStart(field);
  fireEvent.submit(field.closest('form')!);
  expect(api.addMemory).not.toHaveBeenCalled();
  fireEvent.compositionEnd(field);
  fireEvent.submit(field.closest('form')!);
  await waitFor(() => expect(api.addMemory).toHaveBeenCalledWith(1, '🌱'.repeat(1000)));
  await waitFor(() => expect(field).toHaveValue(''));
});
beforeEach(() => { vi.clearAllMocks(); HTMLDialogElement.prototype.showModal = function () { this.setAttribute('open', ''); }; HTMLDialogElement.prototype.close = function () { this.removeAttribute('open'); }; vi.mocked(api.memories).mockResolvedValue([item]); });
it('requires confirmation and does not delete when cancelled', async () => { render(<Memories id={1} close={vi.fn()} />); fireEvent.click(await screen.findByLabelText('删除记忆：喜欢花园')); expect(api.deleteMemory).not.toHaveBeenCalled(); fireEvent.click(screen.getByRole('button', { name: '取消' })); expect(api.deleteMemory).not.toHaveBeenCalled(); });
it('deletes the selected memory only after explicit confirmation', async () => { vi.mocked(api.deleteMemory).mockResolvedValue(null); render(<Memories id={1} close={vi.fn()} />); fireEvent.click(await screen.findByLabelText('删除记忆：喜欢花园')); vi.mocked(api.memories).mockResolvedValue([]); fireEvent.click(screen.getByRole('button', { name: '确认删除' })); await waitFor(() => expect(api.deleteMemory).toHaveBeenCalledWith(9)); expect(await screen.findByText('还没有记忆，把一件小事留在这里吧。')).toBeInTheDocument(); });
it('keeps edited content after failed save', async () => { vi.mocked(api.editMemory).mockRejectedValue(new Error('保存失败')); render(<Memories id={1} close={vi.fn()} />); fireEvent.click(await screen.findByLabelText('编辑记忆：喜欢花园')); const field = screen.getByLabelText('修改这条记忆'); fireEvent.change(field, { target: { value: '喜欢小雨' } }); fireEvent.click(screen.getByRole('button', { name: '保存记忆' })); expect(await screen.findByRole('alert')).toHaveTextContent('保存失败'); expect(field).toHaveValue('喜欢小雨'); });
it('blocks writes until the first memory read completes', async () => {
  vi.mocked(api.memories).mockImplementationOnce(() => new Promise(() => {}));
  render(<Memories id={1} close={vi.fn()} />);
  fireEvent.change(screen.getByLabelText('留下一条记忆'), { target: { value: '不要被旧查询覆盖' } });
  expect(screen.getByRole('button', { name: '保存记忆' })).toBeDisabled();
  fireEvent.submit(screen.getByLabelText('留下一条记忆').closest('form')!);
  expect(api.addMemory).not.toHaveBeenCalled();
});
it('a successful write with failed readback is not presented as a failed write', async () => {
  vi.mocked(api.addMemory).mockResolvedValue({ ...item, id: 10, content: '新的记忆' });
  render(<Memories id={1} close={vi.fn()} />); await screen.findByText('喜欢花园');
  vi.mocked(api.memories).mockRejectedValueOnce(new Error('连接断开'));
  fireEvent.change(screen.getByLabelText('留下一条记忆'), { target: { value: '新的记忆' } });
  fireEvent.click(screen.getByRole('button', { name: '保存记忆' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('操作已完成');
  fireEvent.change(screen.getByLabelText('留下一条记忆'), { target: { value: '新的记忆' } });
  expect(screen.getByRole('button', { name: '保存记忆' })).toBeDisabled();
});
it('an uncertain write retains draft and only retries the read', async () => {
  vi.mocked(api.addMemory).mockRejectedValueOnce(new Error('连接断开'));
  render(<Memories id={1} close={vi.fn()} />); await screen.findByText('喜欢花园');
  fireEvent.change(screen.getByLabelText('留下一条记忆'), { target: { value: '可能已经保存' } });
  fireEvent.click(screen.getByRole('button', { name: '保存记忆' }));
  expect(await screen.findByRole('alert')).toHaveTextContent('核对');
  expect(screen.getByLabelText('留下一条记忆')).toHaveValue('可能已经保存');
  expect(screen.getByRole('button', { name: '保存记忆' })).toBeDisabled();
  fireEvent.click(screen.getByRole('button', { name: '重新加载' }));
  await waitFor(() => expect(api.memories).toHaveBeenCalledTimes(2));
  expect(api.addMemory).toHaveBeenCalledTimes(1);
});
